/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TermProject;

import java.awt.event.KeyEvent;

/**
 *
 * @author Shahla
 */
public class AddOrder extends javax.swing.JFrame {

    /**
     * Creates new form AddOrder
     */
    public AddOrder() {
        initComponents();
        all_panel.setVisible(false);
        coupon_panel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mealType_BG = new javax.swing.ButtonGroup();
        drink_BG = new javax.swing.ButtonGroup();
        clear_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        orderType_CB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serve_TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        price_TF = new javax.swing.JTextField();
        coupon_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        couponId_TF = new javax.swing.JTextField();
        msg_label = new javax.swing.JLabel();
        coupon_CB = new javax.swing.JCheckBox();
        add_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        all_panel = new javax.swing.JPanel();
        dessert_panel = new javax.swing.JPanel();
        prepared_CB = new javax.swing.JCheckBox();
        diabetic_CB = new javax.swing.JCheckBox();
        drink_panel = new javax.swing.JPanel();
        hot_RB = new javax.swing.JRadioButton();
        cold_RB = new javax.swing.JRadioButton();
        alcholic_CB = new javax.swing.JCheckBox();
        meal_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        category_CB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        vegetarian_RB = new javax.swing.JRadioButton();
        chicken_RB = new javax.swing.JRadioButton();
        meat_RB = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clear_button.setText("Clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Order"));

        orderType_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Meal", "Dessert", "Drink" }));
        orderType_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderType_CBActionPerformed(evt);
            }
        });

        jLabel4.setText("Order Type:");

        jLabel2.setText("Serve:");

        serve_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serve_TFActionPerformed(evt);
            }
        });

        jLabel3.setText("Price:");

        coupon_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Coupon"));

        jLabel7.setText("ID:");

        couponId_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couponId_TFActionPerformed(evt);
            }
        });
        couponId_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                couponId_TFKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout coupon_panelLayout = new javax.swing.GroupLayout(coupon_panel);
        coupon_panel.setLayout(coupon_panelLayout);
        coupon_panelLayout.setHorizontalGroup(
            coupon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coupon_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coupon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(msg_label))
                .addGap(28, 28, 28)
                .addComponent(couponId_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        coupon_panelLayout.setVerticalGroup(
            coupon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coupon_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(coupon_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(couponId_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(msg_label)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        coupon_CB.setText("Coupon");
        coupon_CB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                coupon_CBMouseMoved(evt);
            }
        });
        coupon_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coupon_CBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(price_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(orderType_CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serve_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coupon_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coupon_CB))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(orderType_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serve_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(coupon_CB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coupon_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        add_button.setText("ADD");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        close_button.setText("Close");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        all_panel.setLayout(new javax.swing.OverlayLayout(all_panel));

        dessert_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dessert"));

        prepared_CB.setText("Is it prepared?");
        prepared_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prepared_CBActionPerformed(evt);
            }
        });

        diabetic_CB.setText("Diabetic");

        javax.swing.GroupLayout dessert_panelLayout = new javax.swing.GroupLayout(dessert_panel);
        dessert_panel.setLayout(dessert_panelLayout);
        dessert_panelLayout.setHorizontalGroup(
            dessert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dessert_panelLayout.createSequentialGroup()
                .addGroup(dessert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dessert_panelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(prepared_CB))
                    .addGroup(dessert_panelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(diabetic_CB)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        dessert_panelLayout.setVerticalGroup(
            dessert_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dessert_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(prepared_CB)
                .addGap(18, 18, 18)
                .addComponent(diabetic_CB)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        all_panel.add(dessert_panel);

        drink_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Drink"));

        drink_BG.add(hot_RB);
        hot_RB.setText("Hot");

        drink_BG.add(cold_RB);
        cold_RB.setText("Cold");

        alcholic_CB.setText("Alcholic");

        javax.swing.GroupLayout drink_panelLayout = new javax.swing.GroupLayout(drink_panel);
        drink_panel.setLayout(drink_panelLayout);
        drink_panelLayout.setHorizontalGroup(
            drink_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drink_panelLayout.createSequentialGroup()
                .addGroup(drink_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drink_panelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(hot_RB)
                        .addGap(26, 26, 26)
                        .addComponent(cold_RB))
                    .addGroup(drink_panelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(alcholic_CB)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        drink_panelLayout.setVerticalGroup(
            drink_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drink_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(drink_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hot_RB)
                    .addComponent(cold_RB))
                .addGap(18, 18, 18)
                .addComponent(alcholic_CB)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        all_panel.add(drink_panel);

        meal_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Meal"));

        jLabel5.setText("Meal Category:");

        category_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Breakfast", "Lunch", "Dinner" }));

        jLabel6.setText("Meal Type:");

        mealType_BG.add(vegetarian_RB);
        vegetarian_RB.setText("Vegetarian");

        mealType_BG.add(chicken_RB);
        chicken_RB.setText("Chicken");

        mealType_BG.add(meat_RB);
        meat_RB.setText("Meat");

        javax.swing.GroupLayout meal_panelLayout = new javax.swing.GroupLayout(meal_panel);
        meal_panel.setLayout(meal_panelLayout);
        meal_panelLayout.setHorizontalGroup(
            meal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meal_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(category_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(meal_panelLayout.createSequentialGroup()
                .addGroup(meal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meal_panelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel6))
                    .addGroup(meal_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vegetarian_RB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chicken_RB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meat_RB)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        meal_panelLayout.setVerticalGroup(
            meal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meal_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(meal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(category_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addGroup(meal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vegetarian_RB)
                    .addComponent(chicken_RB)
                    .addComponent(meat_RB))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        all_panel.add(meal_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(all_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(all_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serve_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serve_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serve_TFActionPerformed

    private void prepared_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prepared_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prepared_CBActionPerformed

    private void orderType_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderType_CBActionPerformed
        // TODO add your handling code here:
        String str=orderType_CB.getSelectedItem().toString();
        if(str.equalsIgnoreCase("meal")){
            all_panel.setVisible(true);
            meal_panel.setVisible(true);
            dessert_panel.setVisible(false);
            drink_panel.setVisible(false);
        }
        else if(str.equalsIgnoreCase("drink")){
            all_panel.setVisible(true);
            meal_panel.setVisible(false);
            dessert_panel.setVisible(false);
            drink_panel.setVisible(true);
        }
        
        else if(str.equalsIgnoreCase("dessert")){
            all_panel.setVisible(true);
            meal_panel.setVisible(false);
            dessert_panel.setVisible(true);
            drink_panel.setVisible(false);
        }
            
    }//GEN-LAST:event_orderType_CBActionPerformed

    private void coupon_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coupon_CBActionPerformed
        // TODO add your handling code here:
        if(coupon_CB.isSelected())
            coupon_panel.setVisible(true);
        else
            coupon_panel.setVisible(false);
        
        
    }//GEN-LAST:event_coupon_CBActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        String orderType, mealCategory, mealType="", hotOrcold="";
        int couponId, discount, serve;
        boolean alcholic=false, prepared=false, diabetic=false;
        double price;
        
        
        serve=Integer.parseInt(serve_TF.getText());
        price=Double.parseDouble(price_TF.getText());
        
        String str=orderType_CB.getSelectedItem().toString();
        if(str.equalsIgnoreCase("meal")){
            orderType="meal";
            mealCategory=category_CB.getSelectedItem().toString();
            if(vegetarian_RB.isSelected())
                mealType="vegetarian";
            if(meat_RB.isSelected())
                mealType="meat";
            if(chicken_RB.isSelected())
                mealType="chicken";
            
            Meal m=new Meal(serve,price, orderType, mealCategory,mealType);
            OrderSYS.addOrder(m);
            if(checkCoupon()!=null)
            {
                Coupon c=checkCoupon();
                m.addCoupon(c);
                m.setPrice(price-(price*c.getDiscount()/100));
            }
            
            

            
        }
        else if(str.equalsIgnoreCase("drink")){
            orderType="drink";
            if(hot_RB.isSelected())
                hotOrcold="hot";
            if(cold_RB.isSelected())
                hotOrcold="cold";
            if(alcholic_CB.isSelected())
                alcholic=true;
            Drink d=new Drink(serve, price, orderType, hotOrcold, alcholic);
            OrderSYS.addOrder(d);
            if(checkCoupon()!=null)
            {
                Coupon c=checkCoupon();
                d.addCoupon(c);
                d.setPrice(price-(price*c.getDiscount()/100));
            }
        }
        
        else if(str.equalsIgnoreCase("dessert")){
            orderType="dessert";
            if(diabetic_CB.isSelected())
                diabetic=true;
            if(prepared_CB.isSelected())
                prepared=true;
            
            Dessert dt=new Dessert(serve, price, orderType, prepared, diabetic);
            OrderSYS.addOrder(dt);
            
            if(checkCoupon()!=null)
            {
                Coupon c=checkCoupon();
                dt.addCoupon(c);
                dt.setPrice(price-(price*c.getDiscount()/100));
            }
            
           
        }
        
        
        
    }//GEN-LAST:event_add_buttonActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        orderType_CB.setSelectedIndex(0);
        serve_TF.setText(null);
        price_TF.setText(null);
        couponId_TF.setText(null);
        coupon_CB.setSelected(false);
        alcholic_CB.setSelected(false);
        prepared_CB.setSelected(false);
        diabetic_CB.setSelected(false);
        category_CB.setSelectedIndex(0);
        msg_label.setText(null);
        hot_RB.setSelected(false);
        cold_RB.setSelected(false);
        vegetarian_RB.setSelected(false);
        chicken_RB.setSelected(false);
        meat_RB.setSelected(false);
        
        
        
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void couponId_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couponId_TFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_couponId_TFActionPerformed

    private void couponId_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_couponId_TFKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_couponId_TFKeyPressed

    private void coupon_CBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coupon_CBMouseMoved
        // TODO add your handling code here:
        coupon_panel.setVisible(true);
        coupon_CB.setSelected(true);
        
    }//GEN-LAST:event_coupon_CBMouseMoved

    /**
     * @param args the command line arguments
     */
    private Coupon checkCoupon(){
        if(coupon_panel.isVisible()){
            int couponId=Integer.parseInt(couponId_TF.getText());
            int discount=Coupon.getDiscountRate(couponId);
            double price=Double.parseDouble(price_TF.getText());
            if(discount!=0){
                Coupon c=new Coupon(couponId, discount);
                msg_label.setText("Discount Rate: "+discount+"%\n New Price: "+(price-(price*c.getDiscount()/100)));
                return c;                
            }
            else{
                msg_label.setText("No coupon found!");                
            }
        }
        return null;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JCheckBox alcholic_CB;
    private javax.swing.JPanel all_panel;
    private javax.swing.JComboBox<String> category_CB;
    private javax.swing.JRadioButton chicken_RB;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton close_button;
    private javax.swing.JRadioButton cold_RB;
    private javax.swing.JTextField couponId_TF;
    private javax.swing.JCheckBox coupon_CB;
    private javax.swing.JPanel coupon_panel;
    private javax.swing.JPanel dessert_panel;
    private javax.swing.JCheckBox diabetic_CB;
    private javax.swing.ButtonGroup drink_BG;
    private javax.swing.JPanel drink_panel;
    private javax.swing.JRadioButton hot_RB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup mealType_BG;
    private javax.swing.JPanel meal_panel;
    private javax.swing.JRadioButton meat_RB;
    private javax.swing.JLabel msg_label;
    private javax.swing.JComboBox<String> orderType_CB;
    private javax.swing.JCheckBox prepared_CB;
    private javax.swing.JTextField price_TF;
    private javax.swing.JTextField serve_TF;
    private javax.swing.JRadioButton vegetarian_RB;
    // End of variables declaration//GEN-END:variables
}
